### PR TITLE
Integrated change events into the color picker.

### PR DESCRIPTION
**Pull request by jrmobley**
Now the color picker both generates and responds to change events.

This includes the changes previously submitted in pull request #15 from NiVZ78:master.
Also addresses issue #14.

### CODE REVIEW

**Comment by dcormier** [comment]
Is this ever going to be merged? This functionality would solve a problem for me.

**Comment by jrmobley** [comment]
I'm guessing that it won't.

**Comment by Obsouleet** [comment]
It seems to be abandoned. No changes for ages now. This is weird because devs are encouraged to use slate for their apps.  

I need the ability to set a color for a picker, which is  mandatory for an interface like this… but nothing happens.

**Comment by orviwan** [comment]
Slate has been superseded by [Clay](https://github.com/pebble/clay).

**Pull request closed without merging**
